const data = {
  users: [
    {
      name: "Abdur Rahman",
      email: "abdurrahman@gmail.com",
      phone: "01785240648",
      address: "Laxmipura,Raipura,Narsingdi",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "super-admin",
    },
    {
      name: "Abdullah",
      email: "abdullah@gmail.com",
      phone: "01521799244",
      address: "Khainkut,Shibpur,Narsingdi",
      password: "123456",
      isEmailVerified: true,
      isBanned: true,
    },
    {
      name: "MD Salahuddin",
      email: "mdahmede442@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: true,
      role: "user",
    },
    {
      name: "MD Ferdous",
      email: "mdferdous@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Rasel Rana",
      email: "raselrana@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: true,
      role: "user",
    },
    {
      name: "Abdul Alim",
      email: "abdulalim@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "John Smilga",
      email: "johnsmilga@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Kevin Peterson",
      email: "kevinpeterson@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: true,
      role: "user",
    },
    {
      name: "Abdul Ahad",
      email: "abdulahad@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Abu Rayhan",
      email: "aburayhan@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Omar Faruk",
      email: "omarfaruk@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Rimon Mia",
      email: "rimonmia@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Mahmudul Hasan",
      email: "mahmudulhasan@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Abu Bakar",
      email: "abubakar@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Abdus Salam",
      email: "abdussalam@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Miraz",
      email: "miraz@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Ridoy",
      email: "ridoy@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Jaber Khan",
      email: "jaberkhan@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Touhidul Islam",
      email: "touhidulislam@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Monir Hossain",
      email: "monirhossain@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Mubarak Hossain",
      email: "mobarakhossain@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Mostafaur Rahman",
      email: "mustafaur@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Jihad Mia",
      email: "jihadmia@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
    {
      name: "Araf Khan",
      email: "arafkhan@gmail.com",
      address: "Laxmipura,Raipura,Narsingdi",
      phone: "01637038657",
      password: "123456",
      isEmailVerified: true,
      isBanned: false,
      role: "user",
    },
  ],
};

module.exports = data;
